# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='social_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
