# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import photoeditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=photoeditor.models.get_upload_file_name)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='filter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
