# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0002_auto_20160115_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created']},
        ),
    ]
