language: python
python:
- '2.7'
env:
  global:
  - DJANGO_SETTINGS_MODULE='djangobucketlist.settings.test'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- python manage.py collectstatic --noinput --settings=djangobucketlist.settings.test
- python manage.py makemigrations --settings=djangobucketlist.settings.test
- python manage.py migrate --settings=djangobucketlist.settings.test
- python manage.py test --noinput --settings=djangobucketlist.settings.test
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: BSDbnvwNyHkrfIfjsC+BsQ5/6DrsyAZ+FGQ/Dlx9o8Po/an3Vr3HY8aCafaJWAzTs7YDaxxMWhLjdR4biGLBSNihblIMvqtbgQFNK0cpQkCOWnDJ3UCpBIf2zfWZdPO2Nn0w5k2HqT8ReYesQq4kAWv1qG1e9Ntbgu3oZSy6YnizXvVdTyLE1/p6oeLlCjhbCjNvuD9Gcrfr36dF4hGO3gx3R6cZCv2lUsIsJoBCAUdnO0sVhUrWAM4QVbiRO+rSj4NHumI0uGGIdYNyTgyMcTmDdgIk5I8MrgVUMYnsI9imBk02DSLUcmcOdiJxF4JK9bDwo8doa5bCJFMR3VSxwq93UAzqEN9jQgi/k3nNaz01HtprtqghpWYaw15t5cTi4d2wBkRAuYsOoEiazqKW2Yct5yZTXAXHE7Ooe3S1NGy2qilsWhD5nYWG24qjwt2N5HGP/g8v1nkygG/MV22PQ7GJ9F52xjN1eRLl5xVEpVHfbvpH5QpNIxQANanMwR+KhYqm2HHAhMsNbaZTVdSP47BdmIpI+t21ARdQlgVlsFVG4AbIGTsR3PkE943b6ghRhYG3WjstbrRjmhEbtqH+K6x7wjOOH5BTutS2ZOBTAi0ptPSxTUmNpXz+NqEmp8FZ6MN8Ai6cLkYl6vpjWJd6hx/PJI2mQhu4ZX2AiDWpf80=
  app:
    develop: awesomebucket
  skip_cleanup: true
